language: generic 

matrix:
    include:
      - dist: bionic
      - dist: xenial

sudo: required
services: 
    - docker 

before_install:
    - docker build -t plkbnsl/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true plkbnsl/docker-react npm run test
